### ISSUE TITLE
FBchatException: Could not fetch thread 83503671: {u'message_thread': None}

### ISSUE THREAD

**Issue by mattyicer** [punkjj/FB-AutoReply#1]
When running this with python2.7 and having installed FBchat, I was able to login in successfully, however when someone messages me, i get this error: 

```
Traceback (most recent call last):
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/fbchat/client.py", line 2278, in _parseMessage
    thread_id=thread_id, thread_type=thread_type, ts=ts, metadata=metadata, msg=m)
  File "test.py", line 10, in onMessage
    toggle = client.fetchThreadMessages(thread_id=client.uid, limit=1) # client.uid means its our own acc
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/fbchat/client.py", line 845, in fetchThreadMessages
    raise FBchatException('Could not fetch thread {}: {}'.format(thread_id, j))
FBchatException: Could not fetch thread 63593071: {u'message_thread': None}
```

**Comment by JANCOKRAIMUBAWOK** [comment]
IndexError: list index out of range
